# posts/urls.py

from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import PostViewSet, CommentViewSet, FeedView

router = DefaultRouter()

# Registers the PostViewSet for the primary '/posts/' route
router.register(r'posts', PostViewSet, basename='post')

# Registers the CommentViewSet for the primary '/comments/' route
# Note: For simplicity, we use a flat structure. Nested comments (e.g., posts/1/comments/)
# require a slightly more complex approach using drf-nested-routers.
router.register(r'comments', CommentViewSet, basename='comment') 

urlpatterns = [
    # Feed Endpoint
    path('feed/', FeedView.as_view(), name='feed'),
    # Include all routes generated by the router
    path('', include(router.urls)),
]